#!/usr/bin/env julia
# Verifies that the Julia/Flux SRNet produces outputs matching the PyTorch
# reference generated by scripts_python/prepare_srnet_weights.py.
#
# Run the Python script first:
#   cd scripts_python
#   uv run python prepare_srnet_weights.py \
#       --input path/to/JIN_SRNet.pt \
#       --output ../data/pretrained/srnet.h5
#
# Then:
#   julia scripts/test_srnet.jl [--weights path]
#
# Both models run in TRAIN mode so BatchNorm uses batch statistics, avoiding
# the need to synchronise running mean/var from the checkpoint.

using DrWatson
@quickactivate("ClassificationAtTopExperiments.jl")

using Experiments.Flux
using Experiments.HDF5
using Statistics: mean

include(srcdir("Experiments", "src", "srnet.jl"))

function parse_args()
    weights_path = pretraineddir("srnet.h5")
    i = 1
    while i <= length(ARGS)
        if ARGS[i] == "--weights" && i + 1 <= length(ARGS)
            weights_path = ARGS[i+1]; i += 2
        else
            i += 1
        end
    end
    return weights_path
end

weights_path = parse_args()
io_path = weights_path * ".io.h5"

for p in (weights_path, io_path)
    isfile(p) || error("""
File not found: $p
Run first:
  cd scripts_python
  uv run python prepare_srnet_weights.py \\
      --input path/to/JIN_SRNet.pt \\
      --output $weights_path
""")
end

println("Building Julia SRNet (in_channels=3, n_out=2)...")
model = build_srnet(; in_channels=3, n_out=2)
# Stay in train mode (default) so BatchNorm uses batch stats, matching Python.

println("Loading weights from: $weights_path")
load_srnet_weights!(model, weights_path)

x_ref, y_ref = h5open(io_path, "r") do f
    Float32.(read(f, "input")), Float32.(read(f, "output"))
end
println("Input  shape (H,W,C,N): $(size(x_ref))")
println("Output shape (n_out,N): $(size(y_ref))  [Python reference]")

println("\nRunning Julia forward pass...")
y_julia = model(x_ref)

println("\n--- Results ---")
println("Python : $(vec(y_ref)')")
println("Julia  : $(vec(y_julia)')")

abs_diff = abs.(y_julia .- y_ref)
max_diff  = maximum(abs_diff)
mean_diff = mean(abs_diff)
println("\nMax  |Δ| : $max_diff")
println("Mean |Δ| : $mean_diff")

tol = 1f-4
if max_diff < tol
    println("\nPASS — outputs agree within tolerance ($tol)")
else
    println("\nFAIL — max difference $max_diff exceeds tolerance $tol")
    println("""
Likely causes:
  1. β/γ ordering wrong — swap norm.bias / norm.weight pairs in WEIGHT_ORDER
     in scripts_python/prepare_srnet_weights.py and re-run.
  2. Architecture mismatch — add intermediate prints to isolate the block.
  3. Padding / stride mismatch in type3 AvgPool or shortcut conv.
""")
    exit(1)
end
